chore: for gen

diff --git a/.github/workflows/products-publish.yml b/.github/workflows/products-publish.yml
--- a/.github/workflows/products-publish.yml
+++ b/.github/workflows/products-publish.yml
@@ -88,16 +88,15 @@ jobs:
           ref: main
           path: ${{ matrix.product }}
 
-      - name: Set up and check env
+      - name: Setup ${{ matrix.product }} env
         run: |
           source $GITHUB_WORKSPACE/scripts/env.sh
           echo WORK=$WORK >> $GITHUB_ENV
           echo WORKBASE=$WORKBASE >> $GITHUB_ENV
           echo PNAME=${{ matrix.product }} >> $GITHUB_ENV
           echo PATH=$PATH:$GITHUB_WORKSPACE/tools >> $GITHUB_ENV
-          cat $GITHUB_ENV
 
-      - name: Set up go toolchain
+      - name: Setup ${{ matrix.product }} go toolchain
         uses: actions/setup-go@v5
         with:
           go-version: ${{ env.GO_VERSION }}
@@ -105,10 +104,10 @@ jobs:
           cache: true
           cache-dependency-path: "**/*.sum"
 
-      - name: Check go toolchain
+      - name: Check ${{ matrix.product }} go toolchain
         run: go version
                       
-      - name: Preper build code
+      - name: Preper ${{ matrix.product }} build code
         if: ${{ inputs.PUBLISH_VERSION !='' || vars.PUBLISH_VERSION !='' }}
         run: |
           cd $WORK/$PNAME
@@ -133,7 +132,6 @@ jobs:
           echo BUILD_NUMBER=$DYNAMIC_BUILD_NUMBER >> $GITHUB_ENV
           echo EOL=${{ vars.EOL }} >> $GITHUB_ENV
           echo BUILD_DATE=$(date +"%Y-%m-%d %H:%M:%S") >> $GITHUB_ENV
-          cat $GITHUB_ENV
 
       - name: Build ${{ matrix.product }} with ${{ matrix.target }}
         run: cd $WORK/$PNAME && make build-${{ matrix.target }}
@@ -141,10 +139,10 @@ jobs:
       - name: Build ${{ matrix.product }} with ${{ matrix.target }} check
         run: |
           IFS='-' read -r p1 p2 <<< "${{ matrix.target }}"
-          TAG="$WORK/$PNAME/bin/$PNAME-$(echo $p1|sed 's/win/windows/;s/darwin/mac/')-$p2"
+          TAG="$(echo $p1|sed 's/win/windows/;s/darwin/mac/')-$p2"
           [[ "$p1" == "win" ]] && TAG="$TAG.exe"
           ls -alrt $WORK/$PNAME/bin
-          [ -f "$TAG" ] || { echo "Build $PNAME with $p1-$p2 failed" && exit 1; }
+          [ -f "$WORK/$PNAME/bin/$PNAME-$TAG" ] || { echo "Build $PNAME with $p1-$p2 failed" && exit 1; }
 
       - name: Build ${{ matrix.product }} with ${{ matrix.target }} License and notice process
         run: |
@@ -168,16 +166,7 @@ jobs:
           
       - name: Set ${{ matrix.product }} with ${{ matrix.target }} Upload config
         run: |
-          if [ -f $GITHUB_WORKSPACE/.oss.json ] ; then
-              echo "no need init the oss json when file is ready."
-          else
-            cat $GITHUB_WORKSPACE/config/oss.json > $GITHUB_WORKSPACE/.oss.json || true
-          fi
-          if [ -f $GITHUB_WORKSPACE/.oss.yml ] ; then
-            echo "no need init the oss config when file is ready."
-          else
-            cat $GITHUB_WORKSPACE/config/oss.yml > $GITHUB_WORKSPACE/.oss.yml || true
-          fi
+          $GITHUB_WORKSPACE/scripts/gen.sh
           if [[ "$(echo "${{ vars.PRE_RELEASE }}" | tr '[:upper:]' '[:lower:]')" == "true" ]]; then
             grep -wq "pre" $GITHUB_WORKSPACE/.oss.yml || echo "pre: true" >> $GITHUB_WORKSPACE/.oss.yml
           fi
